name: Debug

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Runs on'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  debug:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix-channel --add https://nixos.org/channels/nixos-24.05
          nix-channel --update
      - uses: mxschmitt/action-tmate@v3
        env:
          NIXPKGS_ALLOW_UNFREE: 1
        with:
          limit-access-to-actor: true
