name: Debug

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Runs on'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  debug:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
